### ISSUE TITLE
High priority tags clip the main headers when scrolling on mobile list

### ISSUE THREAD

**Issue by 2amara** [sfbrigade/support-sfusd#133]
When I scroll on the mobile list view, the special tags (high priority) stay above the search/map/list buttons and only disappear when I scroll far past it.
<img src="https://github.com/sfbrigade/support-sfusd/assets/170999239/8bba0571-4673-4f20-b354-07e7762b83d4" width=50% height=50%>
<img src="https://github.com/sfbrigade/support-sfusd/assets/170999239/cdef8d2b-7b7c-4d0a-8705-f03fa480c0a5" width=50% height=50%>

**Comment by nickvisut** [comment]
Good catch, thanks!
