### ISSUE TITLE
Minor visual transparency artifact in header on mobile list view

### ISSUE THREAD

**Issue by nickvisut** [sfbrigade/support-sfusd#135]
Note the see-through part of the header after scrolling up a bit (see screenshot).

<img width="482" alt="Screenshot 2024-05-28 at 2 43 34 AM" src="https://github.com/sfbrigade/support-sfusd/assets/2823112/fa43f166-31bd-4fd4-879b-7d276e01c7b7">

**Comment by javtran** [comment]
@nickvisut I wasn't able to reproduce that result in device toolbar. Are you able to reproduce this visual error?
