### ISSUE TITLE
Selected school in list view doesn't highlight location icon when switching to map view

### ISSUE THREAD

**Issue by j-dubbs** [sfbrigade/support-sfusd#156]
### What happened?

A school is selected in the list view (downtown), but when switching over to map view, the icon on the map is not highlighted in yellow despite the school card being active. 
![image](https://github.com/sfbrigade/support-sfusd/assets/16091151/624d8fd6-4048-4c99-aa5b-46a0147b7fd8)
![image](https://github.com/sfbrigade/support-sfusd/assets/16091151/8ef8c672-c071-4a66-9917-590418297407)

### What should have happened instead?

Map icon should be highlighted in yellow to show actively selected school.
![image](https://github.com/sfbrigade/support-sfusd/assets/16091151/3693f431-0b70-4ccc-9fa7-7a28a7251cb7)

### Version

supportsfschools.org (Production)

### What browser(s) are you seeing the problem on?

Safari, Firefox

### Which platform(s) are you seeing the problem on?

Windows, iOS

**Comment by nickvisut** [comment]
Are this issue and #105 related to each other? @BeeSeeWhy @j-dubbs
