### ISSUE TITLE
[Bug]: Wallenberg form linking to wrong place

### ISSUE THREAD

**Issue by juliagoolia** [sfbrigade/support-sfusd#162]

**Comment by juliagoolia** [comment]
the [Wallenberg volunteer form](https://www.supportsfschools.org/school?name=Wallenberg%20High%20School#volunteer) is linking to the PTA website instead of https://docs.google.com/forms/d/e/1FAIpQLSdlALlSlZCTko4qBryLTunuIVcZGKmVeUl2MA-OPbnoOG15Lg/viewform

**Comment by juliagoolia** [comment]
@nickvisut this is high priority

**Comment by nickvisut** [comment]
@juliagoolia just saw this. FYI I added a "high priority" label to the system. Feel free to rename or add other labels that make sense. And if you see other issues that are also high priority, perhaps you can tag them as well!
