### ISSUE TITLE
replace "event volunteers photo" with new one

### ISSUE THREAD

**Issue by juliagoolia** [sfbrigade/support-sfusd#187]
Will insert Figma link here

**Comment by juliagoolia** [comment]
@j-dubbs can you insert the figma link to the correct photo?

**Comment by j-dubbs** [comment]
[Tutoring Photo](https://www.figma.com/design/5E71m5LhWIH8HhvwuH90mc/Support-SFUSD-Designs?node-id=1-8&t=X2sWdEworeNCtjiU-1)

[Event Volunteer Photo](https://www.figma.com/design/5E71m5LhWIH8HhvwuH90mc/Support-SFUSD-Designs?node-id=1-8&t=X2sWdEworeNCtjiU-1)
