### ISSUE TITLE
(eng spike) faster search results

### ISSUE THREAD

**Issue by juliagoolia** [sfbrigade/support-sfusd#217]
most people we've observed using the site, type in the school name in the search bar rather than finding it on the map or list view. the current search results sometimes take a while to appear (especially the first time typing). for example, start typing "washington" and it would be nice if washington appeared sooner. it would also be nice if typing "oconnell" turned up "o'connell" even though there's an apostrophe.

it probably loads faster after some caching, i don't know the technical details right now.

**Comment by juliagoolia** [comment]
@trushmi i think you were looking at performance issues, so just tagging you here for visibility

**Comment by mattgianni** [comment]
Actually, I got so distracted with improving the speed, I overlooked your other ask -- to ignore symbols, etc during search - or at least stay flexible. Totally doable. I'll submit a new issue and PR for it.
