### ISSUE TITLE
copy update: map page

### ISSUE THREAD

**Issue by juliagoolia** [sfbrigade/support-sfusd#218]
change "San Francisco public schools are closed until mid August. Click on the school closest to you to learn about opportunities in the fall." --> "All schools are looking for volunteers and donations. Click on the school closest to you to learn more."

**Comment by BeeSeeWhy** [comment]
see issue #172   

We may want to make this something we can easily toggle so it's to switch for when school is out of session/summer

**Comment by juliagoolia** [comment]
@nickvisut @BeeSeeWhy @mattgianni can we push this live? See my note in Slack. It's confusing real users! Thx
