### ISSUE TITLE
list view changes order from alphabetical to scrambled

### ISSUE THREAD

**Issue by juliagoolia** [sfbrigade/support-sfusd#223]
the school list view starts out in alphabetical order (Balboa first) and then quickly scrambles to a different order (Galileo first). This is easily reproducible both on mobile and desktop. Here's a screen recording too: https://sfbrigade.slack.com/files/U01JYKWN43D/F07L5J81ZU2/rpreplay_final1725567250.mp4

**Comment by thomhickey** [comment]
@juliagoolia I have this fixed in a branch, happy to push it but I don't yet have permissions. I also can't assign it to myself. @nickvisut or @BeeSeeWhy can you give me repo privs please?

**Comment by thomhickey** [comment]
PR open, waiting for review.
