### ISSUE TITLE
[Bug]: the map page still says schools are closed until mid-August

### ISSUE THREAD

**Issue by nickvisut** [sfbrigade/support-sfusd#243]
### What happened?

Text is out of date as schools have been open for a while as per @trushmi 

### What should have happened instead?

Text should be updated appropriately.

NOTE: The correct changes are already in `develop` (see: https://github.com/sfbrigade/support-sfusd/pull/222), but can't be merged into `main` until branch is deemed to not have regressions.

We can either 1) deploy w/known regression or 2) fix regression that's in `develop` but not `main` (WIP in 
https://github.com/sfbrigade/support-sfusd/pull/244)

### Version

supportsfschools.org (Production)

**Comment by BeeSeeWhy** [comment]
This is fixed with the merging of Develop to Main last week
