### ISSUE TITLE
Refactor School Cards to show volunteer opportunities rather than school stats on map/list view

### ISSUE THREAD

**Issue by BeeSeeWhy** [sfbrigade/support-sfusd#261]
Instead of this: 
![Image](https://github.com/user-attachments/assets/f59ad29f-c3a7-467d-896b-c8ca23c381c1)

we want those to show: 
![Image](https://github.com/user-attachments/assets/05854e0c-e7ee-4570-b74e-e6aeb9d16ab9)

in  that section in stead

**Comment by mattgianni** [comment]
I closed issue by mistake. Reopening.

**Comment by mattgianni** [comment]
I overlooked the "list view" part of the tix. Reopening to make this adjustment.
