### ISSUE TITLE
Standardize Buttons per Design System - CSS [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/support-sfusd#5]
Please use the Figma file -> Design Systems -> buttons for reference. 

Try to standardize all buttons on the app to be in alignment with the Design Systems guidelines for primary, secondary, etc. 

Use your best judgment, but pay special attention to:

 * colors of background and text
 * font characteristics
 * borders and border radii
 * hover and click characteristics

FYI, There are defaults for Material UI that are affecting a few of our buttons

**Comment by rooiss** [comment]
Hey, @tessathornberry was this meant to be added into supportSFUSD? I see the history of this was originally added into the compass project
